const SHEETS={USERS:'Users',BRANCHES:'Branches',RECORDS:'Records',SESSIONS:'Sessions'};
const USER_HEADERS=['userId','loginId','name','passwordHash','salt','role','branchId','active','createdAt','updatedAt'];
const BRANCH_HEADERS=['branchId','name','prefecture','area','mapLat','mapLng','active'];
const RECORD_HEADERS=['id','branchId','lat','lng','fullAddress','personName','status','supporter','revisitPriority','type','date','memo','assigneeId','assigneeName','createdAt','updatedAt','updatedBy'];
const SESSION_HEADERS=['token','userId','expiresAt','createdAt'];

function doGet(){return json_({ok:true,name:'地上戦活動DB Ver.2 API'});}
function doPost(e){try{const p=JSON.parse((e.postData&&e.postData.contents)||'{}');if(p.action==='setup')return json_(setup_(p));if(p.action==='login')return json_(login_(p));const user=auth_(p.token);switch(p.action){case'listRecords':return json_(listRecords_(user));case'saveRecord':return json_(saveRecord_(user,p.record||{}));case'deleteRecord':return json_(deleteRecord_(user,p));case'adminData':return json_(adminData_(user));case'createUser':return json_(createUser_(user,p.user||{}));default:throw Error('不明な処理です');}}catch(err){return json_({ok:false,error:String(err.message||err)});}}

function setup_(p){const ss=SpreadsheetApp.getActive();ensureSheet_(ss,SHEETS.USERS,USER_HEADERS);ensureSheet_(ss,SHEETS.BRANCHES,BRANCH_HEADERS);ensureSheet_(ss,SHEETS.RECORDS,RECORD_HEADERS);ensureSheet_(ss,SHEETS.SESSIONS,SESSION_HEADERS);const bs=ss.getSheetByName(SHEETS.BRANCHES);if(bs.getLastRow()===1)bs.appendRow(['branch_fukuoka_1','福岡第1支部','福岡県','福岡市東区',33.6452,130.4319,true]);const us=ss.getSheetByName(SHEETS.USERS);if(us.getLastRow()===1){const salt=uuid_(),pw=p.adminPassword||'ChangeMe123!';us.appendRow([uuid_(),p.adminLoginId||'admin',p.adminName||'管理者',hash_(pw,salt),salt,'system_admin','',true,now_(),now_()]);}return{ok:true,message:'初期設定が完了しました'};}
function login_(p){cleanupSessions_();const id=String(p.loginId||'').trim(),pw=String(p.password||'');if(!id||!pw)throw Error('ユーザーIDとパスワードを入力してください');const users=rows_(SHEETS.USERS);const u=users.find(x=>String(x.loginId)===id&&truth_(x.active));if(!u||hash_(pw,u.salt)!==u.passwordHash)throw Error('ユーザーIDまたはパスワードが違います');const branch=rows_(SHEETS.BRANCHES).find(b=>b.branchId===u.branchId)||{};const token=uuid_()+uuid_();const expires=new Date(Date.now()+1000*60*60*12).toISOString();SpreadsheetApp.getActive().getSheetByName(SHEETS.SESSIONS).appendRow([token,u.userId,expires,now_()]);return{ok:true,session:{token,userId:u.userId,loginId:u.loginId,name:u.name,role:u.role,branchId:u.branchId,branchName:branch.name||'全支部',expiresAt:expires}};}
function auth_(token){if(!token)throw Error('セッションがありません');cleanupSessions_();const s=rows_(SHEETS.SESSIONS).find(x=>x.token===token);if(!s||new Date(s.expiresAt)<=new Date())throw Error('セッションの有効期限が切れました');const u=rows_(SHEETS.USERS).find(x=>x.userId===s.userId&&truth_(x.active));if(!u)throw Error('利用者が無効です');return u;}
function listRecords_(u){const all=rows_(SHEETS.RECORDS);return{ok:true,records:isGlobal_(u)?all:all.filter(r=>r.branchId===u.branchId)};}
function saveRecord_(u,r){if(!r.fullAddress)throw Error('住所を入力してください');const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.RECORDS),all=rowsWithRow_(SHEETS.RECORDS);let old=all.find(x=>x.id===r.id);if(old&&!canAccessRecord_(u,old))throw Error('この記録は編集できません');if(old&&r.updatedAt&&String(old.updatedAt)!==String(r.updatedAt))throw Error('他の利用者が先に更新しました。最新表示後に編集してください');const now=now_(),branchId=old?old.branchId:(isGlobal_(u)&&r.branchId?r.branchId:u.branchId);const item={id:old?old.id:uuid_(),branchId,lat:r.lat,lng:r.lng,fullAddress:r.fullAddress,personName:r.personName||'',status:r.status||'unvisited',supporter:r.supporter||'',revisitPriority:r.revisitPriority||'',type:r.type||'戸建て',date:r.date||'',memo:r.memo||'',assigneeId:old?old.assigneeId:u.userId,assigneeName:old?old.assigneeName:u.name,createdAt:old?old.createdAt:now,updatedAt:now,updatedBy:u.name};const vals=RECORD_HEADERS.map(h=>item[h]??'');if(old)sh.getRange(old._row,1,1,vals.length).setValues([vals]);else sh.appendRow(vals);return{ok:true,record:item};}
function deleteRecord_(u,p){const all=rowsWithRow_(SHEETS.RECORDS),old=all.find(x=>x.id===p.recordId);if(!old)return{ok:true};if(!canAccessRecord_(u,old))throw Error('削除できません');if(p.updatedAt&&String(old.updatedAt)!==String(p.updatedAt))throw Error('他の利用者が先に更新しました');SpreadsheetApp.getActive().getSheetByName(SHEETS.RECORDS).deleteRow(old._row);return{ok:true};}
function adminData_(u){requireAdmin_(u);const branches=rows_(SHEETS.BRANCHES).filter(b=>truth_(b.active));let users=rows_(SHEETS.USERS);if(u.role==='leader')users=users.filter(x=>x.branchId===u.branchId);const bm=Object.fromEntries(branches.map(b=>[b.branchId,b.name]));return{ok:true,branches:u.role==='leader'?branches.filter(b=>b.branchId===u.branchId):branches,users:users.map(x=>({userId:x.userId,loginId:x.loginId,name:x.name,role:x.role,branchId:x.branchId,branchName:bm[x.branchId]||'全支部',active:truth_(x.active)}))};}
function createUser_(u,x){requireAdmin_(u);if(!x.loginId||!x.name||!x.password)throw Error('必須項目を入力してください');if(rows_(SHEETS.USERS).some(v=>String(v.loginId)===String(x.loginId)))throw Error('同じユーザーIDが登録されています');let role=x.role||'member',branchId=x.branchId||'';if(u.role==='leader'){role=role==='member'?'member':'leader';branchId=u.branchId;}const salt=uuid_();SpreadsheetApp.getActive().getSheetByName(SHEETS.USERS).appendRow([uuid_(),x.loginId,x.name,hash_(x.password,salt),salt,role,branchId,true,now_(),now_()]);return{ok:true};}
function requireAdmin_(u){if(!['leader','prefecture_admin','system_admin'].includes(u.role))throw Error('管理権限がありません');}
function isGlobal_(u){return['prefecture_admin','system_admin'].includes(u.role);}
function canAccessRecord_(u,r){return isGlobal_(u)||r.branchId===u.branchId;}
function ensureSheet_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);sh.setFrozenRows(1);}
function rows_(name){return rowsWithRow_(name).map(x=>{delete x._row;return x;});}
function rowsWithRow_(name){const sh=SpreadsheetApp.getActive().getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v.shift().map(String);return v.map((row,i)=>{const o={_row:i+2};h.forEach((k,j)=>o[k]=row[j]);return o;});}
function cleanupSessions_(){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.SESSIONS);if(!sh||sh.getLastRow()<2)return;const vals=sh.getDataRange().getValues();for(let i=vals.length-1;i>=1;i--)if(new Date(vals[i][2])<=new Date())sh.deleteRow(i+1);}
function hash_(password,salt){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(salt)+'|'+String(password),Utilities.Charset.UTF_8);return bytes.map(b=>(b+256)%256).map(b=>('0'+b.toString(16)).slice(-2)).join('');}
function uuid_(){return Utilities.getUuid().replace(/-/g,'');}function now_(){return new Date().toISOString();}function truth_(v){return v===true||String(v).toLowerCase()==='true'||v===1;}function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
